[Account]
; Nhập tên tài khoản game WLO
Username = your_account

; Nhập mật khẩu game WLO
Password = your_password

[Settings]
; Đường dẫn tới file alogin.exe
GamePath = C:\Users\Tuan\Downloads\WLOI_beta\WLOI\alogin.exe
